name: BrowserStack Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  test_chrome_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK for Chrome
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Use 'adopt' for AdoptOpenJDK
          java-version: '11'     # Specify the desired Java version

      - name: Build with Maven and Run Chrome Tests on Windows
        run: |
          mvn clean test -Dtest=SampleTest -D browserstack.username=${{ secrets.BROWSERSTACK_USERNAME }} -D browserstack.accesskey=${{ secrets.BROWSERSTACK_ACCESS_KEY }} -Dbrowserstack.os=Windows -Dbrowserstack.os_version=10 -Dbrowserstack.browser=chrome -Dbrowserstack.browser_version=latest
