name: SeleniumBrowserStackTests


on:
  push:
    branches:
      - main

jobs:
  test_chrome_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK for Chrome
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'  # Use 'adopt' for AdoptOpenJDK
          java-version: '11'     # Specify the desired Java version

      - name: Set up Chrome browser
        uses: browserstack/github-action@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          os: "Windows"
          os_version: "11"
          browser: "chrome"
          browser_version: "latest"

      - name: Run Selenium Tests
        run: |
          mvn test -Dtest=SampleTest  # Adjust this command as needed

      - name: Clean up Chrome browser
        uses: browserstack/github-action@v2
        with:
          delete: true
